### ISSUE TITLE
awsDummyRequest and concurrency

### ISSUE THREAD

**Issue by danielesegato** [Ghedeon/AwsInterceptor#1]
Hi, coming from stackoverflow I gave a look at your implementation.

Your `awsDummyRequest` in your interceptor assume only 1 call to the interceptor is performed at the same time. This is wrong assumption.

If multiple Http calls are perfomed in parallel they all work on the same instance of `Request` (the `awsDummyRequest`).

You should either create a new request every time or build a pool of reusable request, you create a new one if the others are busy and put the used one in the pool to reuse the objects.

**Comment by Ghedeon** [comment]
Good touch, @danielesegato! Feel free to check the PR.
