### ISSUE TITLE
AWS IoT

### ISSUE THREAD

**Issue by jinman** [Ghedeon/AwsInterceptor#12]
Just curious if I can use this library to do HTTP post requests to AWS IoT. How can we modify this to actually do MQTT publish over websockets using Dagger/Retrofit?

**Comment by Ghedeon** [comment]
Unfortunately, this is out of my field of interest at the moment. If you check the code, it's pretty trivial, all it does is delegate the signing to the original `AWS4Signer` from the amazon library. That might help you to implement your specific version of `Interceptor`.
