### ISSUE TITLE
Android Support Repository Dependancy

### ISSUE THREAD

**Issue by philltomlinson** [Ghedeon/AwsInterceptor#4]
More of a question but when I try to add the example gradle snippet to my build.gradle file it errors with:

```
Error:Could not find com.android.support:support-annotations:25.3.0.
Required by:
    my-project:0.0.1
    my-project:0.0.1 > com.ghedeon:aws-interceptor:0.3

Please install the Android Support Repository from the Android SDK Manager.
```

I don't use the Android SDK as I'm developing a Java application and I can't import this due to project constraints. Is there no way round this?

**Comment by Ghedeon** [comment]
@philltomlinson Ideally yes, an OkHttp interceptor doesn't have to be Android dependant. The thing is, my goal was to be always in sync with aws signing logic and for that, internally I'm just reusing `AWS4Signer` from `aws-android-sdk-apigateway-core`. As you might have guessed, support-annotations is your smallest problem, the real blocker here is `aws-android-sdk-apigateway-core` dependency. But it's an interesting question you raised, I can try to switch to `AWS4Signer` from `aws-java-sdk-core`, this way it will be possible to get rid of android dependencies.

**Comment by Ghedeon** [comment]
Version `0.4` is released. Removed `support-annotations` dependency: https://github.com/Ghedeon/AwsInterceptor/pull/5
Decided to keep `aws-android-sdk-core` dependency, as it has a smaller footprint than `aws-java-sdk-core`. That might prevent you from using the latest tho, let me know if you have any issues.
